apiVersion: v1
kind: Namespace
metadata:
  name: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: infra
  labels:
    tenant: infra
spec:
  loggingRef: infra
  fluentd:
    metrics: {}
  controlNamespace: infra
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: all
  namespace: infra
spec:
  loggingRef: infra
  match:
  - select:
      labels:
        app.kubernetes.io/name: log-generator
  globalOutputRefs:
    - http
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: http
  namespace: infra
spec:
  loggingRef: infra
  http:
    endpoint: http://test-receiver.infra:8080/infra
    content_type: application/json
    buffer:
      type: memory
      timekey: 1s
      timekey_wait: 0s
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: infra
spec:
  loggingRef: infra
  # this is required to reload even if there are pending tasks in one of the queues
  # requires grace to be set, which is 5 by default
  forceHotReloadAfterGrace: true
  inputTail:
    storage.type: filesystem
    storage.pause_on_chunks_overlimit: "off"
  positiondb:
    hostPath:
      path: ""
  bufferStorageVolume:
    hostPath:
      path: ""
  network:
    connectTimeout: 2
    keepaliveMaxRecycle: 20
  metrics: {}
  bufferStorage:
    storage.max_chunks_up: 10
  forwardOptions:
    storage.total_limit_size: 50MB
  image:
    tag: 3.1.10-debug
  configHotReload: {}
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: LoggingRoute
metadata:
  name: tenants
spec:
  source: infra
  targets:
    matchExpressions:
      - key: tenant
        operator: Exists
