apiVersion: v1
kind: Namespace
metadata:
  name: customer-b
  labels:
    tenant: customer-b
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Tenant
metadata:
  name: customer-b
  labels:
    collector: cluster
spec:
  logSourceNamespaceSelectors:
    - matchLabels:
        tenant: customer-b
  subscriptionNamespaceSelectors:
    - matchLabels:
        tenant: customer-b
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Subscription
metadata:
  name: customer-b
  namespace: customer-b
  labels:
    tenant: customer-b
spec:
  condition: "true"
  outputs:
    - name: customer-b-receiver
      namespace: customer-b
---
apiVersion: telemetry.kube-logging.dev/v1alpha1
kind: Output
metadata:
  name: customer-b-receiver
  namespace: customer-b
spec:
  otlp:
    endpoint: receiver-b-collector.customer-b.svc.cluster.local:4317
    tls:
      insecure: true
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: receiver-b
  namespace: customer-b
spec:
  managementState: managed
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      debug:
        verbosity: detailed
    service:
        pipelines:
          logs:
            receivers: [otlp]
            exporters: [debug]
