apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: all-to-file
spec:
  controlNamespace: default
  fluentd:
    disablePvc: true
    bufferStorageVolume:
      pvc:
        source:
          claimName: manual2
          readOnly: false
    extraVolumes:
      - containerName: fluentd
        path: /manual
        volume:
          pvc:
            source:
              claimName: manual
              readOnly: false
        volumeName: manual
      - path: /hostpath
        volume:
          hostPath:
            path: /var/log
      - path: /configmap
        volume:
          configMap:
            name: asdf
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual2
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: manual2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/asd
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual2
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/asd2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: asdf
data:
  asdf.conf: |
    asdf
